on: [push]

name: Rust Build

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - run: RUSTFLAGS="-D warnings" cargo clippy # -- -Wclippy::pedantic
      - run: RUSTFLAGS="-D warnings" cargo build --color=always --all-features
      - run: cargo test --color=always
