[workspace]
members = ["nimble", "assent", "client", "host", "participant", "participant-steps", "steps", "nimble", "seer", "transmute", "freelist", "protocol", "udp-client", "datagram", "udp-connections", "secure-random"]
resolver = "2"

