[workspace]
members = [
    "crates/udp-client",
    "crates/datagram-connections",
    "crates/secure-random",
    "crates/connection-layer",
    "crates/client-with-codec",
    "crates/nimble-snake-client",
]
resolver = "2"
