[workspace]
members = [
    "crates/udp-client",
    "crates/udp-connections",
    "crates/secure-random",
    "crates/connection-layer",
    "crates/nimble-client-cli",
    "crates/example_client",
    ]
resolver = "2"
