use_field_init_shorthand = true
use_try_shorthand = true

# blank_lines_lower_bound = 1
# format_code_in_doc_comments = true
# format_strings = true
# hex_literal_case = "Upper"
# wrap_comments = true
