[package]
name = "datagram"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Datagram traits"
repository = "https://github.com/piot/datagram"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
