[package]
name = "nimble-participant"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Nimble Participant"
repository = "https://github.com/nimble-rust/participant"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
