[package]
name = "nimble-client-connecting"
version = "0.0.1"
edition = "2021"

[dependencies]
nimble-protocol = { path = "../protocol" }
flood-rs = "0.0.10"
log = "0.4.22"

[dev-dependencies]
test-log = "0.2.16"
env_logger = "0.11.5"
