[package]
name = "udp-connections"
version = "0.0.1"
edition = "2021"

[dependencies]
flood-rs = "0.0.10"
datagram = { path = "../datagram" }
secure-random = { path = "../secure-random" }
log = "0.4.22"
