[package]
name = "udp-connections"
version = "0.0.1"
edition = "2021"

[dependencies]
flood-rs = "^0.0.11"
datagram = "^0.0.2"
secure-random = { path = "../secure-random", version = "*" }
log = "^0.4.22"

[dev-dependencies]
test-log = "^0.2.16"
